#! /usr/bin/env ruby

ENV_KEY = "ANYCABLE_THRUSTER_BIN_PATH"
CUSTOM_ANYCABLE_PATH = ENV[ENV_KEY].to_s

if CUSTOM_ANYCABLE_PATH != ""
  begin
    exec(CUSTOM_ANYCABLE_PATH, *ARGV)
  rescue Errno::ENOENT
    warn("ERROR: #{ENV_KEY}=#{CUSTOM_ANYCABLE_PATH.inspect} not found in PATH or as a file.")
    exit 1
  rescue SystemCallError => e
    warn("ERROR: #{ENV_KEY}=#{CUSTOM_ANYCABLE_PATH.inspect} failed: #{e.class}: #{e.message}")
    exit 1
  end
end

PLATFORM = %i[cpu os].map { |m| Gem::Platform.local.send(m) }.join("-")
EXECUTABLE = File.expand_path(File.join(__dir__, PLATFORM, "thrust"))

if File.exist?(EXECUTABLE)
  exec(EXECUTABLE, *ARGV)
else
  warn("ERROR: Unsupported platform: #{PLATFORM}")
  exit 1
end
